// Generated by `make changelog` from CHANGELOG.md — do not edit by hand.
// Re-run `make changelog` (or any `make build*` target) after editing the source.

enum ChangelogData {
    /// The full CHANGELOG.md, baked in at build time. Rendered as Markdown by
    /// the in-app changelog sheet.
    static let markdown = #"""
# Changelog

All notable changes to Clink are recorded here.
The format follows [Keep a Changelog](https://keepachangelog.com/en/1.1.0/),
and the project follows [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

## [1.2.0] - Unreleased

### Added
- **Translate panel.** A new in-keyboard panel that translates what you type
  without leaving the field. Pick a default target language. When Apple
  Intelligence is on and available you can choose the engine (offline language
  packs or Apple Intelligence, the shared `aiTranslate` setting); otherwise it
  falls back to Apple's offline `Translation` framework packs. (`TranslateView`,
  `TranslatePanel`, `TranslateBar`)
- **Custom dictionary.** A hand-curated word list in *Suggestions → Custom*. Add
  your own words so the keyboard always offers them and never "corrects" them.
  Entries are pinned in the `UserAdaptation` store (App Group file, on-device),
  next to the words learning picks up on its own, with per-word delete.
- **Simple / Advanced settings mode.** A toggle on the home screen that hides
  every fine-tune control behind *Advanced* and shows just the essentials in
  *Simple*, across both the container app and the in-extension controls.
- **In-app changelog.** A *CHANGELOG* button in the home footer opens this
  changelog as expandable per-version cards. The text is baked into the app at
  build time from `CHANGELOG.md` (`make changelog`), no network involved.
- **Swipe / glide typing.** Trace a continuous path across the letter keys and it
  decodes into ranked words. The decoder scores each candidate by symmetric
  key-proximity: a *forward* term (every letter visited in order, so an `h→e→y`
  flick doesn't turn into "happy") plus a *reverse coverage* term (every traced
  point explained, so a short word can't win just by matching the trace's
  endpoints). First/last-letter anchoring prunes the dictionary before the
  compare, and word frequency breaks ties toward the commoner word.
  (`SwipeDecoder`, `KeyTouchRouter`)
- **Next-word prediction & completion.** Predictions and completions are ranked
  from bundled n-gram lexicons (unigrams plus bigrams across en/fr/es/de/it/pt/ru,
  built by `make lexicons` from open frequency corpora). The `.clex` files are
  memory-mapped, so a loaded language costs near-zero resident memory until you
  query it, cheap enough to run synchronously on the typing path. (`Lexicon`,
  `Tools/GenerateLexicons.swift`)
- **On-device learning.** Opt-in adaptive store that remembers words you actually
  commit, boosts the ones you accept from the bar, and permanently suppresses
  corrections you reject, so the keyboard stops fighting your vocabulary. One JSON
  file in the App Group, nothing leaves the device, gated by the `learningEnabled`
  setting. (`UserAdaptation`)
- **Apple Intelligence backend.** Optional on-device AI via the `FoundationModels`
  framework (iOS 26+, A17 Pro / M-series). It adds word completions to the
  suggestion bar (gated on `aiEnabled` + `aiCompletions`), optional AI
  auto-correction (`aiAutocorrect`), and powers AI translation in the Translate
  panel. The AI completions augment the instant offline bar asynchronously; they
  never replace it or hold it up, and AI stays off the keystroke hot path. Inference runs
  in an Apple system process, so it works inside the extension without counting
  against its memory cap. Off by default (`aiEnabled`), with full availability
  probing for older OS, ineligible hardware, or Apple Intelligence turned off.
  (`AIEngine`)
- **Custom keys.** Build your own keys in *Layout → Custom*. Insert text (with
  optional Gboard-style long-press alternates) or act as a function key (cursor
  nudge, plane switch, emoji, backspace), placed beside the space bar or in whole
  custom rows above or below the letters. The cap shows a literal string or an SF
  Symbol. (`CustomKey`, `CustomKeysView`)
- **Grid clipboard.** The clipboard panel can render as a grid as well as a list,
  with per-row swipe actions (pin / delete). (`ClipboardPanel`, `SwipeRow`)
- **Motion engine.** A dedicated animation layer (`Motion`, `MotionProfile`,
  `MotionSequence`, `MotionDiagnostics`) behind key-press and panel animations,
  with tunable profiles and a diagnostics path.
- **Key previews & key faces.** Per-key preview rendering and customizable key
  faces, surfaced in the container's *Keys* settings.
- **Suggestion-bar font** setting, a richer interactive in-app keyboard preview,
  and a suggestion-bar padding control.
- **Auto keyboard height.** Height auto-adjusts for the default icon set, with an
  option to hide the suggestion bar entirely.
- New app icon.
- **Multi-language typing.** Pick more than one language in *Localization* and
  type them at once (Spanish *and* English in the same field, say). Offline
  completions, next-word predictions, and swipe-typing vocabulary are merged
  across every active language, and a word is only auto-corrected when it's
  misspelled in *all* of them, so `como` is left alone while English autocorrect
  still fixes `teh` → `the`. The active set is a flat multi-select (at least one
  always on), and the physical key layout is now its own setting instead of being
  force-switched to match the language. All on-device via `UITextChecker`, no
  network. (`KeyboardSettings.keyboardLanguages`, `SuggestionEngine.setLanguages`)
- **Revert auto-correct on delete.** Hitting delete right after an auto-correction
  restores the word you actually typed (type `Dawg`, space corrects it to `Done`,
  delete brings back `Dawg`), and that word is left un-corrected on the next space.
  Matches the native keyboard. New toggle in both *Suggestions* and *Automation*,
  on by default.
- **German (QWERTZ) layout.** A dedicated German keyboard with ü on the top row
  and ö ä on the home row, matching the native layout. Selectable under *Layout →
  Latin*, and auto-paired when you add German as a language. (`KeyboardLayout`)

### Changed
- **Emoji set updated to Unicode 17.0.** The emoji picker now includes the
  latest base emoji (distorted face, orca, treasure chest, trombone, ballet
  dancer, landslide, hairy creature, fight cloud). Regenerated from the vendored
  `Tools/emoji-test.txt` via `make emoji`. New glyphs render on OS versions that
  ship the Unicode 17.0 emoji font; older versions show a placeholder.
- Settings that don't apply to the current configuration are now hidden instead
  of shown disabled, in both the container app and the in-extension controls.

### Fixed
- **Smoother Liquid Glass key presses.** The press bloom keeps its full glass
  lens deformation, but no longer wakes the ~6 surrounding keys so the bulge
  liquid-bleeds into them — that meant ~7 lens re-rasters per spring frame and
  was the press lag, even on a full-power device. The bloom is now isolated to
  the pressed key (one lens re-raster per frame, ~6× cheaper); only the brief
  inter-key bleed on a tap is gone. The swipe ripple keeps its cross-key swell.
  (`KeyView`, `TouchEngine.recomputePressed`)
- **Smoother typing under memory pressure.** The keyboard extension runs in a
  tiny memory sandbox where Liquid Glass — the heaviest layer it composites — is
  the first thing to drop frames, so animations felt less fluid than the same
  views in the app. The extension now watches system memory pressure (a GCD
  memory-pressure source plus `didReceiveMemoryWarning`) and temporarily falls
  back from glass to a solid key render while starved, restoring glass once
  pressure clears. The fallback routes through `MotionProfile` (new
  `setMemoryPressure` / `prefersSolidSurfaces`, applied via `Theme.effective`)
  and is scoped to the extension — the app showcase keeps full-fidelity glass.
- **Dropped keystrokes when typing fast.** A finger that landed during a
  plane/shift layout swap could be silently lost: SwiftUI briefly publishes an
  empty key-frame set while the old key views are torn down and the new ones are
  not yet measured, and the touch router resolved that frame to "no key" and
  discarded the press. The router now double-buffers — it ignores a transient
  empty frame set and keeps the last good layout until a real one arrives — so a
  tap mid-transition still routes to the correct key. (`TouchEngine.update`)
- **Function-key flash.** Fixed a flash on the function keys during plane switches,
  plus App Store compliance for ITMS-90737 / ITMS-90788.
- Settings schema is backward-compatible across upgrades. Older saved configs
  decode without loss (covered by `SettingsBackCompatTests`).
- `make device` now installs onto an iPhone paired over Wi-Fi, not just one cabled
  in. The device-detection step only matched the `connected` state, but a wireless
  pairing reports `available (paired)`, so it would falsely claim "No paired iPhone
  found". It now accepts both states.

### Security
- **New subsystems stay on-device.** The prediction lexicons, swipe decoder, and
  the `UserAdaptation` learning store run entirely locally: bundled data and a JSON
  file in the App Group, no network. The Apple Intelligence backend (`AIEngine`)
  runs inference in an Apple system process on-device; it's off by default
  (`aiEnabled`) and learning is gated by `learningEnabled`. The
  no-network-on-the-typing-path guarantee from 1.0.0 still holds: nothing typed,
  completed, corrected, or learned leaves the device.
- **Translate stays on-device too.** Translation runs through Apple's on-device
  `Translation` framework (or Apple Intelligence). The only network is Apple's own
  one-time language-pack download, handled by the system, not by Clink. The custom
  dictionary is a local App Group file like the rest of `UserAdaptation`.
- Stopped tracking `.wrangler/cache/wrangler-account.json` (it held a Cloudflare
  account id and email) and added `.wrangler/` to `.gitignore`.

## [1.0.0] - 2026-06-04

First production release. A fully customizable, offline-first, privacy-first iOS
keyboard. Two targets (container app plus the `ClinkKeyboard` extension) share one
`ClinkKit`, so the in-app preview is the exact SwiftUI view the extension renders.

### Added
- **Themes.** 30 built-in presets across dark, light, and six **Liquid Glass**
  variants (iOS 26; `.ultraThinMaterial` fallback below 26). Match-system mode
  auto-switches between a chosen light and dark theme.
- **Custom theme builder.** Solid or Liquid Glass material, sans/serif font
  design, per-color pickers, a multi-stop gradient editor (linear / radial), and
  photo backgrounds. Duplicate any preset as a starting point, and export / import
  themes as `.clink` files.
- **Layouts & keys.** Four layouts (QWERTY, AZERTY, QWERTZ, Dvorak); optional
  number row and home-row inset; adjustable key height / width / spacing /
  roundness; standard-balloon or Liquid Glass key popups with tunable position and
  size; a liquid key-press bloom and warp animation with independently tunable
  springs.
- **Offline text assistance.** Autocomplete and auto-correction via `UITextChecker`
  with a Damerau-Levenshtein ranker (no network, no telemetry); smart punctuation
  (curly quotes, double-space → period, contraction apostrophes); auto-capitalize
  and auto-return-to-letters after symbols.
- **Emoji keyboard.** Full Unicode 16.0 set as an internal mode (instant swap, no
  system keyboard transition), name-based search, skin-tone picking with per-emoji
  tone memory, and a recents tab.
- **Clipboard history.** FIFO list with pinning, shown as an inline bar or a
  full-keyboard overlay (needs Full Access to read the pasteboard).
- **Quick notepad.** A scratchpad buffer or a saved-notes archive you can drop text
  into and re-insert anywhere.
- **Panel switcher.** Open clipboard / notepad / emoji panels from the
  suggestion-bar icon or by sliding up on the 123 key; cards or cycling-picker
  style.
- **Sound & haptics.** Per-keypress sound packs (the standard system click works
  without Full Access) with a volume slider; per-keypress haptics (needs Full
  Access).
- **Spacebar cursor.** Slide to move the cursor, in three modes (slide / trackpad /
  combined), with configurable activation delay, scroll sensitivity, and line
  stride.
- **Container app.** Onboarding and a step-by-step enable flow, all settings across
  a four-tab root (Style / Typing / Feel / Setup), a live interactive keyboard
  preview, and whole-config export / import as `.clinkconfig`.
- Device install pipeline (`make device`) and a DEBUG-only marketing-capture
  routing layer (`AppStage`, the [AppStage](https://github.com/anti-ltd/AppStage-MacOS)
  pipeline) that never ships in Release.

### Security & privacy
- **Private by default.** The keyboard works completely without Full Access (you
  get the standard system click) and never transmits anything; there's no network
  code on the typing path.
- All text assistance runs on-device through `UITextChecker`; nothing typed,
  completed, or corrected leaves the device.
- **Full Access is optional** and only gates the two features iOS restricts to it,
  per-keypress haptics and clipboard reads, and nothing else.
- Settings cross the app ↔ extension boundary as a JSON file in the App Group
  (`group.ltd.anti.clink`) via `SharedStore`, not `UserDefaults(suiteName:)`
  (which `cfprefsd` can serve stale across processes).
- No analytics, no crash reporters, no accounts, no identifiers.
"""#
}
