#!/usr/bin/env swift
// Bakes CHANGELOG.md into a Swift source file so the container app can show it
// in-app (the footer "CHANGELOG" button on the home screen) without shipping
// the markdown as a loose bundle resource. Run by `make changelog`; the
// `build*` targets list the output as a prerequisite, so editing CHANGELOG.md
// re-bakes on the next build.
//
//   swift Tools/GenerateChangelog.swift
//
// The markdown is embedded verbatim inside a Swift raw multiline string
// (#"""..."""#) — no escaping needed as long as CHANGELOG.md never contains the
// closing delimiter `"""#`.

import Foundation

let root = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
let srcURL = root.appendingPathComponent("CHANGELOG.md")
let outURL = root.appendingPathComponent("Sources/Clink/Changelog.generated.swift")

guard let markdown = try? String(contentsOf: srcURL, encoding: .utf8) else {
    FileHandle.standardError.write(Data("GenerateChangelog: cannot read \(srcURL.path)\n".utf8))
    exit(1)
}

guard !markdown.contains("\"\"\"#") else {
    FileHandle.standardError.write(Data("GenerateChangelog: CHANGELOG.md contains the raw-string terminator \"\"\"# — bump the delimiter.\n".utf8))
    exit(1)
}

let trimmed = markdown.trimmingCharacters(in: .whitespacesAndNewlines)

let out = """
// Generated by `make changelog` from CHANGELOG.md — do not edit by hand.
// Re-run `make changelog` (or any `make build*` target) after editing the source.

enum ChangelogData {
    /// The full CHANGELOG.md, baked in at build time. Rendered as Markdown by
    /// the in-app changelog sheet.
    static let markdown = #\"\"\"
\(trimmed)
\"\"\"#
}

"""

do {
    try out.write(to: outURL, atomically: true, encoding: .utf8)
    print("GenerateChangelog: wrote \(outURL.path) (\(trimmed.count) chars)")
} catch {
    FileHandle.standardError.write(Data("GenerateChangelog: cannot write \(outURL.path): \(error)\n".utf8))
    exit(1)
}
